### ISSUE TITLE
[MOBILE] APPS ORANGE - DETAIL SURVEI MENAMPILKAN DATA YANG BERBEDA DARI INDEX

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/GOKredit#1]
**Describe the bug**
1. Kalau klik detail survei di halaman pertama, data sama dg yg diklik
2. Tapi kalau klik detail survei setelah klik "muat lebih banyak", datanya beda dg yg diklik

**To Reproduce**
1. Login dg pass admin (2018.0001)
2. Pilih menu survei
3. klik muat lebih banyak, klik detail setelah halaman muat lebih banyak
4. data detailnya beda dengan data yg diklik

**Expected behavior**
Data detailnya sama dengan yang diklik di index

**Screenshots**

[VIDEO.zip](https://github.com/ThunderID/GOKredit/files/2588391/VIDEO.zip)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
 - Device: semua
 - OS: semua
 - Version 4.0.5

**Additional context**
-

**Comment by budi7** [comment]
suspect #7

**Comment by budi7** [comment]
Fixed
updated on : 4.0.8
what to do : bug fixes on lazyload (page stack)
