### ISSUE TITLE
[MOBILE] APPS ORANGE - PIMPINAN TIDAK BISA KLIK SURVEI

### ISSUE THREAD

**Issue by chelsymooy** [ThunderID/GOKredit#2]
**Describe the bug**
akun pimpinan tidak bisa lihat data survei test & live

**To Reproduce**
1. Login dengan akun pimpinan, server test (nip: 2018.0003, pass: pimpinan123)
2. Pilih menu survei
3. Halaman tidak muncul

**Expected behavior**
Pimpinan bisa melihat data survei (hanya melihat tidak mengisi)

**Screenshots**
[VIDEO2.zip](https://github.com/ThunderID/GOKredit/files/2588413/VIDEO2.zip)

**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
 - Device: semua
 - OS: semua
 - Version 4.0.5

**Additional context**
-

**Comment by budi7** [comment]
could be #7

**Comment by budi7** [comment]
Fixed
updated on : 4.0.8
what to do : 
1. fixes on #7 
2. fixes on module to handle users ACL (survei page)
