### ISSUE TITLE
[API, MOBILE] User ganti scope org

### ISSUE THREAD

**Issue by budi7** [ThunderID/GOKredit#7]
Mobile Apps membuat cached data **ID** dari org/koperasi yang terakhir kali diakses oleh user. Data **ID** ini digunakan untuk preload data koperasi, sehingga user tidak perlu memilih terlebih dahulu koperasi mana yang akan diakses, serta pengaturan/pembatasan hak akses/scope.

**Describe the bug**
ID yang ada di cache tidak lagi valid jika data id tersebut tidak lagi termasuk dalam daftar list scope koperasi yang diberikan. Hal ini menyebabkan batasan acl yang diberikan menjadi tidak valid, karena data scope dengan id yang ada di cache tidak dikenali pada daftar list scope yang baru.

**To Reproduce**
_

**Expected behavior**
Apps punya mekanisme _revert to default_ apabila cached id tidak lagi ada pada daftar scope user yang diterima dari API

**Screenshots**
![error 2](https://user-images.githubusercontent.com/10555410/48657774-96111380-ea68-11e8-96f8-afa79bd67ff6.png)
:large_blue_circle: = cached id
:red_circle: = data scope dari API

**Comment by chelsymooy** [comment]
((berkaitan dengan #2 ))
format kode kantor : (YYMM).(000X), 
YYMM adalah tahun dan bulan pembuatan kantor

untuk server test jika beda bulan, memungkinkan beda nomor
misal 1810.0001 pada bulan okt, 1811.0001 pada bulan nov

tapi untuk live ada tidak mungkin beda kode kantor


terkait cache: perlu diperhatikan 
1. jika ybs dimutasi ke kantor lain dan diganti wewenangnya

**Comment by budi7** [comment]
Fixed
updated on :  4.0.8
what to do : add feature to handle if the cached data id is no longer on koperasi list
